#pragma once
#undef VENDOR_ID
#undef PRODUCT_ID
#define VENDOR_ID 0x8F3C
#define PRODUCT_ID 0x2741
#define MASTER_RIGHT
#define LAYER_STATE_8BIT
#ifdef OLED_DRIVER_ENABLE
#define OLED_DISPLAY_128X64
#endif
#ifdef RGBLIGHT_ENABLE
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_MODE_RAINBOW_MOOD
#define RGBLIGHT_MODE_BREATHING
#define RGBLIGHT_MODE_STATIC_GRADIENT
#define RGBLIGHT_MODE_TWINKLE
#define RGBLIGHT_MODE_KNIGHT
#define RGBLIGHT_MODE_SNAKE
#define RGBLIGHT_MODE_RAINBOW_SWIRL
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_LIMIT_VAL 150
#endif
