BOOTMAGIC_ENABLE = lite
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no #breaks on linux
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = yes
SWAP_HANDS_ENABLE = no
OLED_DRIVER_ENABLE = yes
RGB_MATRIX_ENABLE = no
HAPTIC_ENABLE = no
WS2812_DRIVER = pwm #PWM needs patch to <https://github.com/qmk/qmk_firmware/blob/master/platforms/chibios/GENERIC_STM32_F303XC/configs/proton_c.mk>, otherwise defaults to bitbang - See develop PR https://github.com/qmk/qmk_firmware/pull/11864
SERIAL_DRIVER = usart
