// this is the style you want to emulate.
// This is the canonical layout file for the Quantum project. If you want to add another keyboard,

#include QMK_KEYBOARD_H

// Each layer gets a name for readability, which is then used in the keymap matrix below.
// The underscores don't mean anything - you can have a layer called STUFF or any other name.
// Layer names don't all need to be of the same length, obviously, and you can also skip them
// entirely and just use numbers.



//MAKE SURE THESE ARE INCLUDED
#include "artsey.h"
#include "keymap_combo.h"
#include "artsey.c"

enum ferris_layers {
  _RAISE = _FN + 1,
//   _FN,
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_A_BASE] = LAYOUT(A_BASE_S,A_BASE_T,A_BASE_R,A_BASE_A,KC_BSPC,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
A_BASE_O,A_BASE_I,A_BASE_Y,A_BASE_E,OSM(MOD_LSFT),KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
OSM(MOD_LCTL),KC_AT,KC_DEL,KC_EQL,KC_TAB,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
MO(_RAISE),KC_SPC,KC_NO,KC_NO),

[_A_NUM] = LAYOUT(A_NUM_S,A_NUM_T,A_NUM_R,A_NUM_A,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
A_NUM_O,A_NUM_I,A_NUM_Y,A_NUM_E,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_0,KC_9,KC_8,KC_7,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS,KC_NO,KC_NO),

[_A_NAV] = LAYOUT(A_NAV_S,A_NAV_T,A_NAV_R,A_NAV_A,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
A_NAV_O,A_NAV_I,A_NAV_Y,A_NAV_E,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS,KC_NO,KC_NO),

[_A_SYM] = LAYOUT(A_SYM_S,A_SYM_T,A_SYM_R,A_SYM_A,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
A_SYM_O,A_SYM_I,A_SYM_Y,A_SYM_E,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS,KC_NO,KC_NO),

[_A_BRAC] = LAYOUT(A_BRAC_S,A_BRAC_T,A_BRAC_R,A_BRAC_A,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
A_BRAC_O,A_BRAC_I,A_BRAC_Y,A_BRAC_E,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS,KC_NO,KC_NO),

[_A_MOU] = LAYOUT(A_MOU_S,A_MOU_T,A_MOU_R,A_MOU_A,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
A_MOU_O,A_MOU_I,A_MOU_Y,A_MOU_E, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS,KC_NO,KC_NO),

[_A_CUSTOM] = LAYOUT(A_CUSTOM_S,A_CUSTOM_T,A_CUSTOM_R,A_CUSTOM_A,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
A_CUSTOM_O,A_CUSTOM_I,A_CUSTOM_Y,A_CUSTOM_E,KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS,KC_NO,KC_NO),

[_FN] = LAYOUT(KC_F4, KC_F3, KC_F2, KC_F1, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_F8, KC_F7, KC_F6, KC_F5, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_F12, KC_F11, KC_F10, KC_F9, KC_TRNS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_TRNS,KC_NO,KC_NO),

[_RAISE] = LAYOUT(KC_CIRC,KC_LCBR,KC_RCBR,KC_HASH,KC_GRAVE,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_AMPR, KC_LPRN, KC_RPRN, KC_DOLLAR, KC_BSLS,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_ASTR,KC_LBRC, KC_RBRC, KC_PERC, KC_PIPE,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
KC_TRNS, KC_SCLN,KC_NO,KC_NO),



};

