#pragma once

#define NO_AUTO_SHIFT_MODIFIERS
#define NO_AUTO_SHIFT_SPECIAL
#define AUTO_SHIFT_TIMEOUT 170
#define NO_AUTO_SHIFT_NUMERIC

#define TAPPING_TERM 155
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERUPT

#define COMBO_COUNT 10
#define COMBO_TERM 40
#define RGB_LIMIT_VAL 100

#define UNICODE_SELECTED_MODES UC_WINC, UC_MAC, UC_LNX
#define UNICODE_CYCLE_PERSIST false

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 80

/*#undef DISABLE_TERRAZZO_EFFECT_DOT
#undef DISABLE_TERRAZZO_EFFECT_HEART
#undef DISABLE_TERRAZZO_EFFECT_PAC_DUDE*/
