MCU = atmega32u4
#BOOTLOADER = nano-boot
#BOOTLOADER_SIZE = 512
BOOTLOADER = atmel-dfu
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = no
OLED_DRIVER_ENABLE = no
GRAVE_ESC_ENABLE = no
EXTRAKEY_ENABLE = no
LTO_ENABLE = yes
WPM_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
SPACE_CADET_ENABLE = no
SPLIT_KEYBOARD_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
AUTO_SHIFT_ENABLE = no
SWAP_HANDS_ENABLE = no
CONSOLE_ENABLE = no
COMBO_ENABLE = yes
BOOTMAGIC_ENABLE = no
TAP_DANCE_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
KEYLOGGER_ENABLE = yes
ifdef POINTING_DEVICE_ENABLE
	SRC += i2c_master.c
endif
